app = "zahara-v1-qdrant"
primary_region = "iad"

[build]
  image = "qdrant/qdrant:latest"

[env]
  QDRANT__SERVICE__HOST=::
  QDRANT__SERVICE__HTTP_PORT = "6333"

[mounts]
  source = "qdrant_data"
  destination = "/qdrant/storage"

[[services]]
  internal_port = 6333
  processes = ["app"]
  protocol = "tcp"

[http_service]
  internal_port = 6333
  auto_start_machines = true
  auto_stop_machines = true